# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courseorg_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='\u5168\u56fd\u77e5\u540d\u529e\u5b66\u673a\u6784', max_length=30, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
