# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('desc', models.CharField(max_length=100, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('detail', models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5')),
                ('degree', models.CharField(choices=[('low', '\u521d\u7ea7'), ('mid', '\u4e2d\u7ea7'), ('high', '\u9ad8\u7ea7')], max_length=6)),
                ('learn_times', models.IntegerField(default=0, validators='\u5b66\u4e60\u65f6\u957f\uff0c\u5355\u4f4d\u5206\u949f')),
                ('students', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('collection_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='\u8bfe\u7a0b\u5c01\u9762\u56fe ')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u70b9\u51fb\u6570\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u4fe1\u606f',
                'verbose_name_plural': '\u8bfe\u7a0b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u8bfe\u7a0b\u8d44\u6e90\u540d\u79f0')),
                ('download', models.FileField(upload_to='course/resource/%Y/%d', verbose_name='\u8bfe\u7a0b\u5bf9\u5e94\u7684\u8d44\u6e90\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90\u4fe1\u606f',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7ae0\u8282\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282\u4fe1\u606f',
                'verbose_name_plural': '\u7ae0\u8282\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='\u7ae0\u8282\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u4fe1\u606f',
                'verbose_name_plural': '\u89c6\u9891\u4fe1\u606f',
            },
        ),
    ]
