# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8bfe\u7a0b\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8bfe\u7a0b\u8d44\u6e90\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8bfe\u7a0b\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u89c6\u9891\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
