# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170916_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f\u5355\u4f4d\u5206\u949f'),
        ),
    ]
