# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('1', '\u524d\u7aef\u5f00\u53d1'), ('2', '\u540e\u7aef\u5f00\u53d1'), ('3', '\u79fb\u52a8\u5f00\u53d1'), ('4', '\u6570\u636e\u5e93'), ('5', '\u8fd0\u7ef4&\u6d4b\u8bd5')], default='1', max_length=20, verbose_name='\u8bfe\u7a0b\u5206\u7c7b'),
        ),
    ]
