# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='www.baidu.com', max_length=200, verbose_name='\u89c6\u9891\u8def\u5f84'),
        ),
    ]
