# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170923_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_kno',
            field=models.CharField(default='\u6211\u77e5\u9053\u4f60\u5168\u90fd\u77e5\u9053', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_learn',
            field=models.CharField(default='\u80fd\u5b66\u5230\u4ec0\u4e48\uff0c\u4f60\u77e5\u9053\u8fd8\u4e0d\u6e05\u695a\u5417\uff1f', max_length=300, verbose_name='\u4f60\u80fd\u5b66\u5230\u4ec0\u4e48'),
        ),
    ]
